# Generated by Django 6.0.4 on 2026-05-06 09:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('last_name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
            ],
            options={
                'db_table': 'EXTERNAL_PROFESSIONAL',
            },
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='Lugar de trabajo')),
            ],
            options={
                'db_table': 'WORK_PLACE',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('role_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol del trabajador')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'db_table': 'WORKER',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FamilyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=50, unique=True, verbose_name='Nº Expediente')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('external_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_cases', to='core.externalprofessional')),
            ],
            options={
                'db_table': 'FAMILY_CASE',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol Familiar')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('last_name2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidad')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('derivation', models.BooleanField(default=False, verbose_name='Derivación')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro escolar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('family_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='core.familycase')),
            ],
            options={
                'db_table': 'BENEFICIARY',
            },
        ),
        migrations.CreateModel(
            name='TrainingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la acción')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('stop_time', models.TimeField(verbose_name='Hora de fin')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TRAINING_ACTION',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='enrolled_groups', to='core.beneficiary')),
                ('training_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.trainingaction')),
            ],
            options={
                'db_table': 'GROUP',
            },
        ),
        migrations.AddField(
            model_name='externalprofessional',
            name='work_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='core.workplace'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de la sesión')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('JUSTIFIED_ABSENCE', 'Falta Justificada'), ('UNJUSTIFIED_ABSENCE', 'Falta Injustificada')], default='PRESENT', max_length=20, verbose_name='Estado')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.beneficiary')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.group')),
            ],
            options={
                'db_table': 'ATTENDANCE',
                'unique_together': {('group', 'beneficiary', 'date')},
            },
        ),
    ]
