# Generated by Django 6.0.4 on 2026-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_beneficiary_options_alter_worker_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='Es tutor/a legal'),
        ),
    ]
