# Generated by Django 6.0.4 on 2026-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_beneficiary_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='incidence_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de incidencia'),
        ),
    ]
