# Generated by Django 6.0.4 on 2026-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attendance_incidence_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='familycase',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Expediente archivado'),
        ),
    ]
